POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
  "longUrl": "https://www.amazon.com/b?node=16225007011&pf_rd_r=E4BF39Z2NEH2Z88VAVT2&pf_rd_p=e5b0c85f-569c-4c90-a58f-0c0a260e45a0&pd_rd_r=1a07be3c-38c8-4618-b22d-191001a090d1&pd_rd_w=PvPyW&pd_rd_wg=cIq9S&ref_=pd_gw_unk"
}